spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nawa5
    username: root
    password: QhrtnswoTkddl1!6
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update

logging:
  level:
    org.hibernate.sql: debug
